// server/src/seed/services.seed.js
// Retail pricing = base * 3 (profit x3)

export const servicesSeed = [
  // ===================== INSTAGRAM =====================
  {
    name: "Instagram Followers",
    category: "Instagram",
    type: "followers",
    unit: "follower",
    min: 50,
    max: 100000,
    ratePer1000: 12.0, // base: 4.0 -> retail: 12.0
    description: "High-quality followers. Start: 50+. Delivery: gradual. No password needed.",
    requiresText: false,
    status: "active",
  },
  {
    name: "Instagram Likes",
    category: "Instagram",
    type: "likes",
    unit: "like",
    min: 50,
    max: 100000,
    ratePer1000: 6.0, // base: 2.0 -> retail: 6.0
    description: "Post likes. Works for public posts. Start: 50+.",
    requiresText: false,
    status: "active",
  },
  {
    name: "Instagram Views (Post)",
    category: "Instagram",
    type: "views_post",
    unit: "view",
    min: 100,
    max: 500000,
    ratePer1000: 3.0, // base: 1.0 -> retail: 3.0
    description: "Views for IG posts. Start: 100+. Fast delivery.",
    requiresText: false,
    status: "active",
  },
  {
    name: "Instagram Reels Views",
    category: "Instagram",
    type: "views_reels",
    unit: "view",
    min: 100,
    max: 500000,
    ratePer1000: 3.0, // base: 1.0 -> retail: 3.0
    description: "Reels views. Start: 100+. Stable delivery.",
    requiresText: false,
    status: "active",
  },
  {
    name: "Instagram Comments",
    category: "Instagram",
    type: "comments",
    unit: "comment",
    min: 10,
    max: 5000,
    ratePer1000: 150.0, // base: 50.0 -> retail: 150.0 (10 = 1.50)
    description: "Realistic comments. Provide the comment text(s) you want bots to post.",
    requiresText: true,
    status: "active",
  },

  // ===================== TIKTOK =====================
  {
    name: "TikTok Followers",
    category: "TikTok",
    type: "followers",
    unit: "follower",
    min: 50,
    max: 100000,
    ratePer1000: 12.0, // align with IG for now (can tweak later)
    description: "TikTok followers. Start: 50+. Gradual delivery.",
    requiresText: false,
    status: "active",
  },
  {
    name: "TikTok Likes",
    category: "TikTok",
    type: "likes",
    unit: "like",
    min: 50,
    max: 200000,
    ratePer1000: 6.0,
    description: "TikTok likes. Start: 50+.",
    requiresText: false,
    status: "active",
  },
  {
    name: "TikTok Views",
    category: "TikTok",
    type: "views",
    unit: "view",
    min: 100,
    max: 1000000,
    ratePer1000: 3.0,
    description: "TikTok video views. Start: 100+.",
    requiresText: false,
    status: "active",
  },
  {
    name: "TikTok Comments",
    category: "TikTok",
    type: "comments",
    unit: "comment",
    min: 10,
    max: 5000,
    ratePer1000: 150.0,
    description: "TikTok comments. Provide comment text(s).",
    requiresText: true,
    status: "active",
  },

  // ===================== YOUTUBE =====================
  {
    name: "YouTube Subscribers",
    category: "YouTube",
    type: "subscribers",
    unit: "subscriber",
    min: 50,
    max: 100000,
    ratePer1000: 30.0, // base: 10.0 -> retail: 30.0 (50 = 1.50)
    description: "YouTube subscribers. Start: 50+. Gradual delivery.",
    requiresText: false,
    status: "active",
  },
  {
    name: "YouTube Views",
    category: "YouTube",
    type: "views",
    unit: "view",
    min: 100,
    max: 5000000,
    ratePer1000: 30.0, // base: 10.0 -> retail: 30.0 (100 = 3.00)  ✅ po tvom: 100 views = 1.00 base
    description: "YouTube views. Start: 100+. Stable delivery.",
    requiresText: false,
    status: "active",
  },
  {
    name: "YouTube Live Viewers (15 min)",
    category: "YouTube",
    type: "live_viewers_15m",
    unit: "viewer",
    min: 50,
    max: 5000,
    ratePer1000: 30.0, // base: 10.0 -> retail: 30.0 (50 = 1.50) ✅ po tvom: 50 viewers/15min = 0.50 base
    description: "Live viewers for 15 minutes. Start: 50 viewers. Good for boosting engagement.",
    requiresText: false,
    status: "active",
  },
  {
    name: "YouTube Comments",
    category: "YouTube",
    type: "comments",
    unit: "comment",
    min: 10,
    max: 5000,
    ratePer1000: 150.0, // base: 50 -> retail:150 (10 = 1.50)
    description: "YouTube comments. Provide comment text(s) for bots.",
    requiresText: true,
    status: "active",
  },

  // ===================== FACEBOOK =====================
  {
    name: "Facebook Page Likes",
    category: "Facebook",
    type: "page_likes",
    unit: "like",
    min: 50,
    max: 100000,
    ratePer1000: 18.0, // slightly higher than IG
    description: "Facebook page likes. Start: 50+.",
    requiresText: false,
    status: "active",
  },
  {
    name: "Facebook Post Likes",
    category: "Facebook",
    type: "post_likes",
    unit: "like",
    min: 50,
    max: 200000,
    ratePer1000: 9.0,
    description: "Facebook post likes. Start: 50+.",
    requiresText: false,
    status: "active",
  },
  {
    name: "Facebook Followers",
    category: "Facebook",
    type: "followers",
    unit: "follower",
    min: 50,
    max: 100000,
    ratePer1000: 18.0,
    description: "Facebook profile/page followers. Start: 50+.",
    requiresText: false,
    status: "active",
  },

  // ===================== TWITTER / X =====================
  {
    name: "X (Twitter) Followers",
    category: "Twitter/X",
    type: "followers",
    unit: "follower",
    min: 50,
    max: 50000,
    ratePer1000: 24.0,
    description: "X followers. Start: 50+. Gradual delivery.",
    requiresText: false,
    status: "active",
  },
  {
    name: "X (Twitter) Likes",
    category: "Twitter/X",
    type: "likes",
    unit: "like",
    min: 50,
    max: 100000,
    ratePer1000: 12.0,
    description: "X post likes. Start: 50+.",
    requiresText: false,
    status: "active",
  },
  {
    name: "X (Twitter) Retweets",
    category: "Twitter/X",
    type: "retweets",
    unit: "retweet",
    min: 50,
    max: 50000,
    ratePer1000: 15.0,
    description: "Retweets. Start: 50+.",
    requiresText: false,
    status: "active",
  },

  // ===================== TELEGRAM =====================
  {
    name: "Telegram Channel Members",
    category: "Telegram",
    type: "members",
    unit: "member",
    min: 50,
    max: 200000,
    ratePer1000: 15.0,
    description: "Telegram channel members. Start: 50+.",
    requiresText: false,
    status: "active",
  },
  {
    name: "Telegram Post Views",
    category: "Telegram",
    type: "views",
    unit: "view",
    min: 100,
    max: 2000000,
    ratePer1000: 3.0,
    description: "Telegram views on channel posts. Start: 100+.",
    requiresText: false,
    status: "active",
  },

  // ===================== SPOTIFY =====================
  {
    name: "Spotify Plays",
    category: "Spotify",
    type: "plays",
    unit: "play",
    min: 100,
    max: 5000000,
    ratePer1000: 6.0,
    description: "Spotify plays. Start: 100+. Gradual delivery.",
    requiresText: false,
    status: "active",
  },
  {
    name: "Spotify Followers",
    category: "Spotify",
    type: "followers",
    unit: "follower",
    min: 50,
    max: 200000,
    ratePer1000: 15.0,
    description: "Spotify profile followers. Start: 50+.",
    requiresText: false,
    status: "active",
  },

  // ===================== SNAPCHAT =====================
  {
    name: "Snapchat Followers",
    category: "Snapchat",
    type: "followers",
    unit: "follower",
    min: 50,
    max: 50000,
    ratePer1000: 18.0,
    description: "Snapchat followers. Start: 50+.",
    requiresText: false,
    status: "active",
  },
  {
    name: "Snapchat Story Views",
    category: "Snapchat",
    type: "views",
    unit: "view",
    min: 100,
    max: 1000000,
    ratePer1000: 6.0,
    description: "Snap story views. Start: 100+.",
    requiresText: false,
    status: "active",
  },

  // ===================== DISCORD =====================
  {
    name: "Discord Server Members",
    category: "Discord",
    type: "members",
    unit: "member",
    min: 50,
    max: 200000,
    ratePer1000: 18.0,
    description: "Discord server members. Start: 50+.",
    requiresText: false,
    status: "active",
  },

  // ===================== WEBSITE TRAFFIC =====================
  {
    name: "Website Traffic (Worldwide)",
    category: "Website Traffic",
    type: "traffic",
    unit: "visit",
    min: 1000,
    max: 1000000,
    ratePer1000: 9.0,
    description: "Website visits. Start: 1,000. Good for exposure & analytics.",
    requiresText: false,
    status: "active",
  },

  // ===================== OTHER =====================
  {
    name: "Other (Coming soon)",
    category: "Other",
    type: "coming_soon",
    unit: "unit",
    min: 1,
    max: 1,
    ratePer1000: 0,
    description: "More services coming soon.",
    requiresText: false,
    status: "inactive",
  },
];
